### PR TITLE
Chaining conditionals to avoid checking string value twice

### PR DESCRIPTION
**Pull request by tcarrio**
And removed breaks. Same logic and processes the string only once if `prompt.strip()=='public'`, since there's just no need to check the same variable to see if it equals some value if you've already determined it's something else.

### CODE REVIEW

**Comment by chulderman** [comment]
How does it leave the while loop? the logic is there, but I'm not sure why it would exit the loop given what you've written.

**Comment by tcarrio** [comment]
``` python
for ...
    if prompt.strip() == 'public':
        build = 'public'
        break
```

If you need to break from the loop then yeah I'll fix that.

Edit: I EVEN THOUGHT IT WAS  A FOR LOOP.

**Comment by tcarrio** [comment]
So I don't know how that managed to happen. Oops.

**Comment by chulderman** [comment]
Yeah, good work. You made it look prettier.

**Comment by tcarrio** [comment]
# Thanks

**Comment by tcarrio** [comment]
# <3

**Pull request merged**
